### PR TITLE
more posts and /blog.html

### PR DESCRIPTION
**Pull request by todrobbins**

### CODE REVIEW

**Comment by rufuspollock** [comment]
Fantastic!

**Comment by todrobbins** [comment]
Ack! Just noticed the link in the menu to the blog is wrong. Sending another pull your way!

**Comment by rufuspollock** [comment]
@todrobbins i note you are now invited as a contribute to this repo so you can merge yourself.

**Comment by todrobbins** [comment]
PHEW. ;-)

**Pull request merged**
